@startuml tables

!define Table(name,desc) entity name as "desc" << (T,#FFAAAA) >>

Table(users,"users\nユーザー") {
  + id [PK]
  --
  name [ユーザー名]
  email [メールアドレス]
  password [パスワード]
  created_at [作成日]
  updated_at [更新日]
}

' 2次開発に回す
' Table(goals,"goals\n学習目標時間") {
'   + id [PK]
'   --
'   # user_id [FK]
'   day_of_week [曜日]
'   target_time [目標学習時間]
'   created_at [作成日]
'   updated_at [更新日]
' }

Table(daily_summaries,"daily_summaries\n１日の実学習時間") {
  + id [PK]
  --
  # user_id [FK]
  date [日付]
  total_actual_time [総実学習時間]
  created_at [作成日]
  updated_at [更新日]
}

Table(study_sessions,"study_sessions\n実学習時間") {
  + id [PK]
  --
  # user_id [FK]
  # daily_summary_id [FK]
  start_time [開始時間]
  end_time [終了時間]
  actual_time [実時間]
  created_at [作成日]
  updated_at [更新日]
}

Table(daily_study_sessions,"daily_study_sessions\n学習実績view") {
  --
  # user_id [FK]
  # daily_summary_id [FK]
  date [日付]
  start_time1 [開始時間1]
  end_time1 [終了時間1]
  start_time2 [開始時間2]
  end_time2 [終了時間2]
  start_time3 [開始時間3]
  end_time3 [終了時間3]
  total_actual_time [実時間]
}
@enduml
