@startuml erd
!include time_trucker_display.pu

skinparam Linetype ortho

header --> study_new
header -r-> user_edit
header -r-> sign_in
sign_in --> sign_up
sign_in --> study_new
sign_up --> sign_in
user_edit --> study_new
study_new --> study_index
' 二次開発に回す
' study_new -l-> schedule
study_index --> study_edit
study_edit --> study_index

@enduml