@startuml erd
!include time_trucker_table.pu

skinparam Linetype ortho

' 2次開発に回す
' users ||-l-o{ goals
users ||-r-o{ daily_summaries
users ||-l-o{ study_sessions
users ||-d-o{ daily_study_sessions
daily_summaries ||--|| daily_study_sessions

@enduml