@startuml displays

!define Display(name, desc) entity name as "desc" << (D,#5f9ea0) >>

Display(header, "ヘッダー") {
  ・学習時間ボタンをクリック
  __
  ・ログインボタンをクリック
  __
  ・ログアウトボタンをクリック
  __
  ・ユーザー情報編集ボタンをクリック
}
package "ユーザー関連の実装" <<Rectangle>> #ffe4b5 {

  Display(sign_up, "新規登録") {
    ・ユーザー情報入力欄
    __
    ・新規登録ボタンをクリック
    __
    ・ログインページへのリンクをクリック
  }

  Display(sign_in, "ログイン") {
    ・ログイン情報入力欄
    __
    ・必須項目を入力し、ログインボタンをクリック
    __
    ・新規登録ボタンをクリック
  }

  Display(user_edit, "ユーザー情報編集") {
    ・ユーザー情報入力欄
    __
    ・必須項目を入力し、登録ボタンをクリック
  }

}

package "学習管理画面の実装" <<Rectangle>> #b0c4de {

  Display(study_new, "学習時間打刻") {
    ・開始ボタンをクリック
    __
    ・終了ボタンをクリック
    __
    ・学習時間一覧ボタンをクリック
    ' 二次開発に回す
    ' __
    ' ・学習計画編集ボタンをクリック
  }

  Display(study_index, "学習時間一覧") {
    ・表示年月日選択ボタンをクリック
    __
    ・詳細ボタンをクリック
  }

  Display(study_edit, "学習時間詳細") {
    ・打刻を修正するボタンをクリック
    __
    ・戻るボタンをクリック
  }

' 二次開発に回す
  ' Display(schedule, "学習計画") {
  '   ・登録するボタンをクリック
  ' }

}
@enduml
